# Generated by Django 4.2.10 on 2024-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Discount Price'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Satatus'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Discount status'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_audience',
            field=models.CharField(choices=[('all', 'all'), ('tutor', 'Tutor'), ('learning_center', 'Learning Center')], default='all', max_length=20, verbose_name='Service audience'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('top', 'Top'), ('premium', 'Premium')], default='top', max_length=12, verbose_name='Service type'),
        ),
    ]
