# Generated by Django 4.2.10 on 2024-12-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_discount_price_service_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
    ]
