# Generated by Django 4.2.10 on 2025-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
    ]
