# Generated by Django 4.2.10 on 2025-03-24 18:23

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicetranslation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('slider_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'sliders',
                'ordering': ['slider_order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SliderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('image_large', imagekit.models.fields.ProcessedImageField(upload_to='slider', verbose_name='Image (1216x388)')),
                ('image_medium', imagekit.models.fields.ProcessedImageField(upload_to='slider', verbose_name='Image (728x410)')),
                ('link', models.CharField(max_length=500, verbose_name='Link')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.slider')),
            ],
            options={
                'verbose_name': 'Slider Translation',
                'db_table': 'sliders_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
