version: '3'

volumes:
  ustoz_local_announcements_postgres: {}
  ustoz_local_announcements_postgres_backups: {}
  ustoz_local_users_postgres: {}
  ustoz_local_users_postgres_backups: {}

services:
  admin:
    build:
      context: .
      dockerfile: ./images/admin/compose/local/admin/Dockerfile
    image: ustoz_local_admin
    container_name: ustoz_local_admin
    depends_on:
      - redis
      - announcements_postgres
      - users_postgres
    volumes:
      - ./images/admin:/app:z
    env_file:
      - ./images/admin/.envs/.local/.admin
      - ./images/admin/.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
  
  announcements_api:
    build:
      context: .
      dockerfile: ./images/announcements/compose/local/api/Dockerfile
    image: ustoz_local_announcement_api
    container_name: ustoz_local_announcement_api
    depends_on:
      - announcements_postgres
      - users_postgres
      - redis
    volumes:
      - ./images/announcements:/app:z
    env_file:
      - ./images/announcements/.envs/.local/.api
      - ./images/announcements/.envs/.local/.postgres
    ports:
      - '8080:8080'
    command: /start
  
  users_api: &users_api
    build:
      context: .
      dockerfile: ./images/users/compose/local/api/Dockerfile
    image: ustoz_local_users_api
    container_name: ustoz_local_users_api
    depends_on:
      - users_postgres
      - announcements_postgres
      - redis
    volumes:
      - ./images/users:/app:z
    env_file:
      - ./images/users/.envs/.local/.api
      - ./images/users/.envs/.local/.postgres
    ports:
      - '5000:5000'
    command: /start

  announcements_postgres:
    build:
      context: .
      dockerfile: ./images/announcements/compose/production/postgres/Dockerfile
    image: ustoz_production_announcements_postgres
    container_name: ustoz_local_announcements_postgres
    volumes:
      - ustoz_local_announcements_postgres:/var/lib/postgresql/data
      - ustoz_local_announcements_postgres_backups:/backups
    env_file:
      - ./images/announcements/.envs/.local/.postgres

  users_postgres:
    build:
      context: .
      dockerfile: ./images/users/compose/production/postgres/Dockerfile
    image: ustoz_production_users_postgres
    container_name: ustoz_local_users_postgres
    volumes:
      - ustoz_local_users_postgres:/var/lib/postgresql/data
      - ustoz_local_users_postgres_backups:/backups
    env_file:
      - ./images/users/.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: ustoz_local_redis

  celeryworker:
    <<: *users_api
    image: ustoz_local_celeryworker
    container_name: ustoz_local_celeryworker
    depends_on:
      - redis
      - users_postgres
      - announcements_postgres
    ports: []
    command: /start-celeryworker
