# Generated by Django 4.2.10 on 2024-09-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Phone number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Price')),
                ('lessons_in_week', models.IntegerField(verbose_name='Lessons in a week')),
                ('lesson_duration_hours', models.IntegerField(verbose_name='Lesson duration')),
                ('lesson_type', models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], max_length=10, verbose_name='Lesson type')),
                ('lesson_place', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=10, verbose_name='Lesson place')),
                ('lesson_language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2, verbose_name='Lesson language')),
                ('lesson_audience', models.CharField(blank=True, choices=[('children', 'Children'), ('adults', 'Adults'), ('all', 'All')], max_length=10, null=True, verbose_name='Lesson audience')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('is_confirmed_by_admin', models.BooleanField(default=False, verbose_name='Admin confirmation')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Promotion status')),
                ('promotion_started', models.DateField(blank=True, null=True, verbose_name='Promotion start date')),
                ('promotion_expired', models.DateField(blank=True, null=True, verbose_name='Promotion expire date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'announcement',
            },
        ),
    ]
