# Generated by Django 4.2.10 on 2024-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Not active'), ('waiting', 'Waiting'), ('rejected', 'Rejected')], default='waiting', max_length=20, verbose_name='Status'),
        ),
    ]
