# Generated by Django 4.2.10 on 2024-11-11 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=10)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('finish_year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_year', models.DateField()),
                ('finish_year', models.DateField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ManyToManyField(related_name='learning_centers', to='members.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('web_link', models.CharField(blank=True, max_length=255, null=True)),
                ('insta_link', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified_by_admin', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_started', models.DateField(blank=True, null=True)),
                ('premium_expired', models.DateField(blank=True, null=True)),
                ('location_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('learning_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to='members.learningcenter')),
            ],
            options={
                'unique_together': {('learning_center', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
            options={
                'db_table': 'user_role_association',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='members.UserRoleAssociation', to='members.role'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.ManyToManyField(blank=True, related_name='tutors', to='members.education')),
                ('experience', models.ManyToManyField(blank=True, related_name='tutors', to='members.experience')),
                ('language', models.ManyToManyField(blank=True, related_name='tutors', to='members.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='members.user')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_center', to='members.user'),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='working_schedule',
            field=models.ManyToManyField(related_name='learning_centers', to='members.workingschedule'),
        ),
        migrations.AddField(
            model_name='language',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='members.tutor'),
        ),
        migrations.AddField(
            model_name='experience',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='members.tutor'),
        ),
        migrations.AddField(
            model_name='education',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='members.tutor'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.user')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='learning_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='members.learningcenter'),
        ),
        migrations.CreateModel(
            name='LoginHistoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_type', models.CharField(default='web', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
            options={
                'db_table': 'login_history',
                'unique_together': {('id', 'device_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='learningcenter',
            unique_together={('user',)},
        ),
    ]
