# Generated by Django 4.2.10 on 2024-11-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningcenter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_center', to='members.user'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='members.user'),
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
        migrations.AlterModelTable(
            name='education',
            table='education',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='experience',
        ),
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
        migrations.AlterModelTable(
            name='learningcenter',
            table='learning_center',
        ),
        migrations.AlterModelTable(
            name='tutor',
            table='tutor',
        ),
        migrations.AlterModelTable(
            name='workingschedule',
            table='working_schedule',
        ),
        migrations.RemoveField(
            model_name='learningcenter',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='learningcenter',
            name='working_schedule',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='language',
        ),
    ]
