# Generated by Django 4.2.10 on 2025-03-02 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_usertag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('object_id', models.IntegerField()),
                ('service_id', models.UUIDField()),
            ],
            options={
                'db_table': 'content_types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], max_length=10)),
                ('payment_gateway', models.CharField(blank=True, choices=[('payme', 'Payme'), ('click', 'Click'), ('paynet', 'Paynet'), ('wallet', 'Wallet')], max_length=10, null=True)),
                ('payment_gateway_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_gateway_time', models.BigIntegerField(blank=True, null=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('canceled_at', models.BigIntegerField(blank=True, default=0, null=True)),
                ('performed_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.contenttypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.user')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
